config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index'
  devise_for :users
  root to: "pages#home"

  post 'calculate_emissions', to: 'pages#calculate_emissions'
  get 'dashboard', to: 'pages#dashboard'

  resources :shipments, only: [:index, :new, :create, :edit, :update, :destroy, :show]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert custom-alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>


<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"> </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="wrapper-footer">
  <p>&copy; EcoWheels 2023. All rights reserved.</p>
  <i class="fab fa-instagram"></i>
  <i class="fab fa-twitter"></i>
  <i class="fab fa-facebook-f"></i>
</div>

app/views/shared/_master_navbar.html.erb
<% if (controller_name == 'pages' && action_name.in?(['home', 'dashboard'])) || (controller_name == 'shipments' && action_name.in?(['index', 'edit', 'new', 'show'])) %>
  <div class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
      <div class="title-page">
        <%= link_to root_path, class: "navbar-brand" do %>
          <h1>EcoWheels
            <%= image_tag "earth_logo.png", class: "logo", style: 'height: 50px; width: auto;' %>
          </h1>
        <% end %>
      </div>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#shipmentsNavbar" aria-controls="shipmentsNavbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="shipmentsNavbar">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item <%= 'active' if controller_name == 'pages' && action_name.in?(['home', 'dashboard']) %>">
              <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item <%= 'active' if controller_name == 'shipments' && action_name == 'index' %>">
              <%= link_to "My Shipments", shipments_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= image_tag "burger.png", class: "avatar", alt: "dropdown menu" %>
              </a>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Add a Shipment", new_shipment_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>