config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index'
  devise_for :users
  root to: "pages#home"

  post 'calculate_emissions', to: 'pages#calculate_emissions'
  get 'dashboard', to: 'pages#dashboard'

  resources :shipments, only: [:index, :new, :create, :edit, :update, :destroy, :show]
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  include PgSearch::Model
  include DistanceHelper

  before_validation :geocode_start_and_end
  before_validation :calculate_distance
  before_validation :calculate_emissions

  belongs_to :user

  has_many_attached :photos

  after_initialize :set_default_status, if: :new_record?

  validates_presence_of :distance_traveled, :vehicle_type, :fuel_type,
                        :fuel_consumption, :product_name, :shipment_start,
                        :shipment_end, :co2_emissions

  validates_numericality_of :distance_traveled, :fuel_consumption, :co2_emissions
  validates_presence_of :start_location, :end_location

  before_save :set_city_to_end_location

  pg_search_scope :search,
                  against: [:city, :distance_traveled, :vehicle_type, :fuel_type, :product_name],
                  using: {
                    tsearch: { prefix: true }
                  }

  enum status: { "scheduled" => "scheduled", "completed" => "completed", "canceled" => "canceled" }

  private

  def calculate_distance
    self.distance_traveled = haversine_distance(
      self.start_latitude,
      self.start_longitude,
      self.end_latitude,
      self.end_longitude
    ).round(2)
  end

  def calculate_emissions
    emission_service = EmissionCalculatorService.new

    self.fuel_consumption = emission_service.calculate_fuel_consumption(vehicle_type)
    self.co2_emissions = emission_service.call(self)
    pp emission_service.call(self)
  end

  def geocode_start_and_end
    if start_location
      geocoded = Geocoder.search(start_location).first
      if geocoded
        self.start_latitude = geocoded.latitude
        self.start_longitude = geocoded.longitude
      end
    end

    if end_location
      geocoded = Geocoder.search(end_location).first
      if geocoded
        self.end_latitude = geocoded.latitude
        self.end_longitude = geocoded.longitude
      end
    end
  end

  def set_city_to_end_location
    self.city = self.end_location
  end

  def set_default_status
    self.status ||= :scheduled
  end
end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  include DistanceHelper

  def index

    @total_shipments = current_user.shipments.count
    @shipments = current_user.shipments
    @shipment = Shipment.new
    @shipments = filter_shipments(@shipments)

    if params[:sort_by]
      @shipments = sort_shipments(@shipments)
    end

    if params[:query].present?
      @shipments = @shipments.search(params[:query])
    end

    if params[:status].present?
      @shipments = @shipments.where(status: params[:status])
    end

    @shipments = policy_scope(@shipments)
  end

  #comment

  def new
    @shipment = Shipment.new
    authorize @shipment
  end

  def create
    @shipment = Shipment.new(shipment_params)
    @shipment.user = current_user
    authorize @shipment

    if @shipment.save
      redirect_to shipments_path
    else
      render :new, status: :unprocessable_entity
    end
  end


  def show
    @shipment = Shipment.find(params[:id])
    authorize @shipment

    @markers = [
      { lat: @shipment.start_latitude, lng: @shipment.start_longitude, popup: 'Start Location',

        info_window_html: render_to_string(partial: "info_window", locals: {shipment: @shipment, location: @shipment.start_location})

      },

      {lat: @shipment.end_latitude, lng: @shipment.end_longitude, popup: 'End Location',

      info_window_html: render_to_string(partial: "info_window", locals: {shipment: @shipment, location: @shipment.end_location})
      },
    ]
  end

  def edit
    @shipment = Shipment.find(params[:id])
    authorize @shipment
  end

  def update
    @shipment = Shipment.find(params[:id])
    @shipment.update(shipment_params)
    authorize @shipment

    respond_to do |format|
      if @shipment.save
        format.html { redirect_to shipments_path}
        format.json { render json: { status: "success"} }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: { status: "error", message: "Failed to update shipment." }, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @shipment = Shipment.find(params[:id])

    authorize @shipment

    if current_user == @shipment.user
      if @shipment.destroy
        redirect_to shipments_path
      else
        redirect_to shipments_path, alert: "Error deleting shipment."
      end
    else
      redirect_to shipments_path, alert: "You are not authorized to delete this Shipment."
    end
  end


  private

  def shipment_params
    params.require(:shipment).permit(:product_name, :city, :shipment_start, :shipment_end, :vehicle_type, :fuel_type, :start_location, :end_location, :distance_traveled, :status, photos: [])
  end

  def sort_shipments(shipments)
    shipments.order(params[:sort_by])
  end

  def filter_shipments(shipments)
    shipments = shipments.where(city: params[:city]) if params[:city].present?
    shipments = shipments.where(vehicle_type: params[:vehicle_type]) if params[:vehicle_type].present?
    shipments = shipments.where(fuel_type: params[:fuel_type]) if params[:fuel_type].present?
    shipments = shipments.where(product_name: params[:product_name]) if params[:product_name].present?
    shipments = shipments.where("shipment_start >= ?", params[:shipment_start]) if params[:shipment_start].present?
    shipments = shipments.where("shipment_end <= ?", params[:shipment_end]) if params[:shipment_end].present?
    shipments = shipments.where(co2_emissions: params[:co2_emissions]) if params[:co2_emissions].present?
    shipments
  end
end

app/views/shipments/_form.html.erb
<div class="form-inputs">
  <% if @shipment.errors.any? %>
    <% @shipment.errors.full_messages.each do |error| %>
      <p style="color: red"><%= error %></p>
    <% end %>
  <% end %>
  <%= simple_form_for @shipment, html: { id: "new_shipment" }, data: { controller: 'flatpickr' } do |f| %>
    <%= f.input :product_name %>
    <%# <%= f.input :city %>
    <%= f.input :shipment_start, as: :string, input_html: { data: { flatpickr_target: "startTime" } } %>
    <%= f.input :shipment_end, as: :string, input_html: { data: { flatpickr_target: "endTime" } } %>
    <%= f.input :vehicle_type, as: :select, collection: ['4 Cylinder', '6 Cylinder', '8 Cylinder', 'Heavy Truck', 'Medium Truck'] %>
    <%= f.input :fuel_type, as: :select, collection: ['Gasoline', 'Diesel'], label: 'Fuel Type' %>
    <%= f.input :start_location %>
    <%= f.input :end_location %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%# Only show for update %>
    <% if @shipment.persisted? %>
      <%= f.hidden_field :distance_traveled, id: 'distance_traveled' %>
    <% end %>

    <%= f.button :submit, 'Submit', class: 'btn btn-light custom-bg-blue' %>
  <% end %>

</div>

app/views/shipments/_form_modal.html.erb
<div class="form-inputs">
  <% if shipment.errors.any? %>
    <% @shipment.errors.full_messages.each do |error| %>
      <p style="color: red"><%= error %></p>
    <% end %>
  <% end %>

  <%= simple_form_for shipment, html: { id: "new_shipment" }, data: { controller: 'flatpickr sweet-alert' } do |f| %>
    <div class="form-field product-name">
      <%= f.input :product_name, input_html: { style: 'width: 605px; text-align: left; margin-bottom: 5px; margin-top: 25px;', placeholder: 'Product Name' }, label: false %>
    </div>
    <div class="form-field">
      <div class="date-field">
        <%= f.input :shipment_start, as: :string, input_html: { data: { flatpickr_target: "startTime" }, placeholder: 'Shipment Start' }, label: false %>
        <%= f.input :shipment_end, as: :string, input_html: { data: { flatpickr_target: "endTime" }, placeholder: 'Shipment End' }, label: false %>
      </div>
    </div>

    <div class="form-field">
      <div class="date-field">
        <%= f.input :vehicle_type, as: :select, collection: ['4 Cylinder', '6 Cylinder', '8 Cylinder', 'Heavy Truck', 'Medium Truck'], prompt: 'Select Vehicle Type', label: false %>
        <%= f.input :fuel_type, as: :select, collection: ['Gasoline', 'Diesel'], prompt: 'Select Fuel Type', label: false %>
      </div>
    </div>

    <div class="form-field">
      <div class="date-field">
        <%= f.input :start_location, input_html: { placeholder: 'Start Location' }, label: false %>
        <%= f.input :end_location, input_html: { placeholder: 'End Location' }, label: false %>
      </div>
    </div>


    <%# Only show for update %>
    <% if shipment.persisted? %>
      <div class="form-field">
        <%= f.hidden_field :distance_traveled, id: 'distance_traveled' %>
      </div>
    <% end %>

    <%= f.button :submit, 'Submit', class: 'btn btn-light custom-bg-blue', data: { action: "click->sweet-alert#initSweetalert" } %>
  <% end %>
</div>

app/views/shipments/_form_new.html.erb
<div class="form-inputs">
  <% if @shipment.errors.any? %>
    <% @shipment.errors.full_messages.each do |error| %>
      <p style="color: red"><%= error %></p>
    <% end %>
  <% end %>

  <%= simple_form_for @shipment, html: { id: "new_shipment" }, data: { controller: 'flatpickr sweet-alert' } do |f| %>
    <div class="form-field product-name">
      <%= f.input :product_name, input_html: { style: 'width: 600px; text-align: left;', placeholder: 'Product Name' }, label: false %>
    </div>
    <div class="form-field">
      <div class="date-field">
        <%= f.input :shipment_start, as: :string, input_html: { data: { flatpickr_target: "startTime" }, placeholder: 'Shipment Start' }, label: false %>
        <%= f.input :shipment_end, as: :string, input_html: { data: { flatpickr_target: "endTime" }, placeholder: 'Shipment End' }, label: false %>
      </div>
    </div>

    <div class="form-field">
      <div class="date-field">
        <%= f.input :vehicle_type, as: :select, collection: ['4 Cylinder', '6 Cylinder', '8 Cylinder', 'Heavy Truck', 'Medium Truck'], prompt: 'Select Vehicle Type', label: false %>
        <%= f.input :fuel_type, as: :select, collection: ['Gasoline', 'Diesel'], prompt: 'Select Fuel Type', label: false %>
      </div>
    </div>

    <div class="form-field">
      <div class="date-field">
        <%= f.input :start_location, input_html: { placeholder: 'Start Location' }, label: false %>
        <%= f.input :end_location, input_html: { placeholder: 'End Location' }, label: false %>
      </div>
    </div>

    <div class="form-field">
      <%= f.input :photos, as: :file, input_html: { multiple: true, style: 'width: 600px', placeholder: 'Upload Photos' }, label: false %>
    </div>

    <%# Only show for update %>
    <% if @shipment.persisted? %>
      <div class="form-field">
        <%= f.hidden_field :distance_traveled, id: 'distance_traveled' %>
      </div>
    <% end %>

    <%= f.button :submit, 'Submit', class: 'btn btn-light custom-bg-blue', data: { action: "click->sweet-alert#initSweetalert" } %>
  <% end %>
</div>

app/views/shipments/_info_window.html.erb
<h4 style="font-size: 1.5rem; margin: 0;"><%= location %></h4>
<p style="font-size: 1rem; margin: 0;"> Total CO<sub>2</sub> Emissions: <%= shipment.co2_emissions.to_s %></p>

app/views/shipments/edit.html.erb
<%= render "shared/master_navbar" %>
<%# <div class="card-edit-form col-lg-3 d-flex flex-row" style="width: 30rem; margin: 0 auto; margin-top: 3rem; margin-bottom: 3rem; padding: 1rem"> %>
<div class="container-banner">
</div>




 <div class="row">
  <div class="col-lg-6">
   <div class="container-card-edit">
    <div class="card-edit" style=" m-0 auto ; mt-3;">
      <div class="title-page" style="mt-2 ; mb-1 ; ml-2 ; text-center"><h2>Edit Your Shipment</h2></div>
        <div class="card-form-edit " style="mt-5 ; ml-4 ; p-0 auto;">
        <%= render "form_new" %>
      </div>
    </div>
   </div>
  </div>
  </div>
 </div>




<%# <div class="container-bottom-cards">
<div class="row">
<div class="col-lg-6">
   <div class="container-bottom-edit">
     <div class="text-page" style="text-center pt-3;">
     <h4>Here are 5 ways to reduce your carbon footprint significantly 🌿</h4>
     <h6>
     <ul><li>Avoid Mass Market, Throw Away Fashion.</li></ul>
     <ul><li> Reduce your Meat and Diary Consumption.</li></ul>
     <ul><li>Refuse Single-Use Plastic.</li></ul>
     <ul><li>Reduce and Rethink your Transportation.</li></ul>
     <ul><li> Switch to Green Energy.</li></ul>
     <ul><li>Fighting Climate Change through Rewilding.</li></ul>
     </h6>
    </div>
  </div>
 </div>


  <div class="container-bottom-edit-2">
    </div>
    </div>
</div> %>

app/views/shipments/new.html.erb
<%= render "shared/master_navbar" %>

<div class= "container-new">
  <div class="container-banner"> </div>
</div>

<div style="display: flex; justify-content: center;">
  <div class="modal-wrapper-final">
    <div class="modal-header-final">
      <h1>Add Your Shipment</h1>
    </div>
    <%= render "form_new" %>
  </div>
</div>

app/views/shipments/show.html.erb
<% content_for :meta_title, "#{@shipment.city} is on #{DEFAULT_META["meta_name"]}" %>
<% content_for :meta_description, @shipment.product_name %>
<%# <% content_for :meta_image, cl_image_path(@shipment.end_location) if @shipment.end_location %>

<%= render "shared/master_navbar" %>

<div class="container-banner"></div>

<div class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
      <ul class="navbar-nav me-auto">
        <li class="nav-item custom-padding-left">
          <%= link_to "Back to Shipments", shipments_path, class: "nav-link", class: "btn btn-outline-secondary my-3" %>
        </li>
      </ul>
  </div>
</div>

<div class="container mt-5">
  <div class="row content-row">

    <!-- Shipment Info -->
          <%# <div class="row"> %>

          <!-- Left side -->
          <%# <div class="col-6"> %>

    <!-- Shipment Info -->
        <div class="col-md-6 p-4 info-container">
      <div class="showpage-card shadow">
        <div class="showpage-card-body">
          <span class="card-author subtle">The shipment product</span>
          <h2 class="showpage-card-title"><%= @shipment.product_name %></h2>
          <ul class="list-unstyled mt-4">
            <li>📍 City - <strong><%= @shipment.city %></strong></li>
            <li>🌍 Distance - <strong><%= @shipment.distance_traveled %></strong> </li>
            <li>🚚 Vehicle - <strong><%= @shipment.vehicle_type %></strong></li>
            <li>⛽ Fuel - <strong><%= @shipment.fuel_type %></strong></li>
            <li>📈 Fuel consump - <strong><%= @shipment.fuel_consumption %> l</strong></li>
            <li>📅 Shipment Start - <strong><%= @shipment.shipment_start ? @shipment.shipment_start.strftime("%A, %d %b %Y") : "N/A" %></strong></li>
            <li>📆 Shipment End - <strong><%= @shipment.shipment_end ? @shipment.shipment_end.strftime("%A, %d %b %Y") : "N/A" %></strong></li>
            <li>📊 CO2 - <strong><%= @shipment.co2_emissions %></strong></li>
            <li class="mt-2 text-muted">Last updated <%= time_ago_in_words @shipment.updated_at %></li>
          </ul>

          <div class="mt-3">
            <%= link_to shipment_path(@shipment), data: { controller: "delete-confirmation", action: "click->delete-confirmation#confirm" }, class: 'btn btn-outline-danger bin-icon' do %>
              <i class="fa fa-pencil fa-trash teal-color"></i>
            <% end %>
            <%# <%= link_to edit_shipment_path(@shipment), class: 'btn btn-outline-primary ml-2' do %>
              <i class="fa fa-pencil teal-color"></i>
            <%# <% end %> 
          </div>
            <div class="card-read"></div>
            <span class="card-tag card-circle subtle">C</span>
        </div>
      </div>
    </div>

    <!-- Map -->
      <div class="col-md-6 map-wrapper p-4">
        <div class="map-container shadow" data-controller="map" data-map-markers-value="<%= @markers.to_json %>" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>
    </div>

  <!-- Return to previous page -->
  <%# <div class="row mt-4 p-4">
    <div class="col-12">
      <%= link_to "Return to the previous page", shipments_path, class: "btn btn-outline-secondary" %>
    <%# </div>
  </div> %>
</div>